In [1]:
#OneHotEncoding

In [4]:
from sklearn.preprocessing import OneHotEncoder

In [33]:
import numpy as np
import pandas as pd
df = pd.DataFrame(["man bites dog","dog bites man","dog bites man"],columns =['col'])
# text = np.array(["man bites dog","dog bites man","dog bites man"])
x = OneHotEncoder()
encoded = x.fit_transform(df[['col']])

In [34]:
print(encoded)

  (0, 1)	1.0
  (1, 0)	1.0
  (2, 0)	1.0


In [36]:
pd.get_dummies(df[['col']])

col_dog bites man  col_man bites dog
0                  0                  1
1                  1                  0
2                  1                  0

In [37]:
#BagOfWords

In [38]:
df.head()

col
0  man bites dog
1  dog bites man
2  dog bites man

In [61]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
bow  = cv.fit_transform(df['col'])

In [62]:
print(cv.vocabulary_)

{'man': 2, 'bites': 0, 'dog': 1}


In [63]:
bow[0].toarray()

array([[1, 1, 1]])

In [67]:
bow[1].toarray()

array([[1, 1, 1]])

In [68]:
df2 = pd.DataFrame(["man","dog","eat","dog","man","meat"],columns =['col'])
df2.head()

col
0  man
1  dog
2  eat
3  dog
4  man

In [69]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
bow  = cv.fit_transform(df2['col'])

In [70]:
cv.vocabulary_

{'man': 2, 'dog': 0, 'eat': 1, 'meat': 3}

In [72]:
bow[0].toarray()

array([[0, 0, 1, 0]])

In [73]:
bow[1].toarray()

array([[1, 0, 0, 0]])

In [76]:
cv.transform(["dog dog"]).toarray()

array([[2, 0, 0, 0]])

In [77]:
cv.transform(["eat meat eat"]).toarray()

array([[0, 2, 0, 1]])

In [3]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
df3 = pd.DataFrame(["man bites dog","dog bites man","dog bites man"],columns =['col'])
df3.head()

col
0  man bites dog
1  dog bites man
2  dog bites man

In [6]:
cv = CountVectorizer(ngram_range=(1,3))
bow = cv.fit_transform(df3['col'])


In [7]:
bow[0].toarray()

array([[1, 1, 0, 1, 0, 0, 1, 1, 1]])

In [12]:
cv.vocabulary_

{'man': 6,
 'bites': 0,
 'dog': 3,
 'man bites': 7,
 'bites dog': 1,
 'man bites dog': 8,
 'dog bites': 4,
 'bites man': 2,
 'dog bites man': 5}

In [9]:
bow[1].toarray()

array([[1, 0, 1, 1, 1, 1, 1, 0, 0]])

In [11]:
cv.transform(['dog bites dog bites man']).toarray()

array([[2, 1, 1, 2, 2, 1, 1, 0, 0]])

In [14]:
#TF-IDF

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [16]:
tfidf = TfidfVectorizer()
tf = tfidf.fit_transform(df3['col'])


In [17]:
tf[0].toarray()

array([[0.57735027, 0.57735027, 0.57735027]])

In [18]:
tfidf.transform(['dog bites man']).toarray()

array([[0.57735027, 0.57735027, 0.57735027]])

In [19]:
tfidf.transform(['dog man bites']).toarray()

array([[0.57735027, 0.57735027, 0.57735027]])